module.exports = {
  apps: [
    {
      name: "leadsGuadalupana",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3007,
        NEXT_BASE_PATH: "/leads",
        NEXTAUTH_URL: "https://servicios.guadalupana.com.gt/leads",
        NEXTAUTH_SECRET: "L5Uax35utm3S9lxzlKFee3Y+tklWKorri1WuoXseoFU=",
        LDAP_URL: "ldap://172.20.1.69",
        LDAP_BASE_DN: "DC=guadalupana,DC=com,DC=gt",
        LDAP_SERVICE_USER: "pgssantisteban@guadalupana.com.gt",
        LDAP_SERVICE_PASS: "octubre.2024",
        SQL_SERVER: "172.20.1.70",
        PORTSQL: "1433",
        SQL_USER: "Genexus",
        SQL_PASSWORD: "T3chn0l0gy",
        SQL_DB: "BankworksPhoenix",
      },
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "500M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "./logs/error.log",
      out_file: "./logs/out.log",
      merge_logs: true,
    },
    {
      name: "leadsGuadalupana-agencia",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3008,
        NEXT_BASE_PATH: "/agencia",
      },
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "500M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "./logs/error-agencia.log",
      out_file: "./logs/out-agencia.log",
      merge_logs: true,
    },
  ],
};
