module.exports = {
  apps: [
    {
      name: "leadsGuadalupana",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      env: {
        SQL_ENCRYPT: "true",
        SQL_TRUST_SERVER: "true",
        SQL_POOL_MAX: "10",
        SQL_POOL_MIN: "0",
        SQL_POOL_IDLE: "30000",
        NEXTAUTH_MAX_AGE: "2592000",
        NODE_ENV: "production",
        PORT: 3007,
        NEXT_BASE_PATH: "/leads",
        NEXTAUTH_URL: "https://servicios.guadalupana.com.gt/leads",
        NEXTAUTH_SECRET: "L5Uax35utm3S9lxzlKFee3Y+tklWKorri1WuoXseoFU=",
        LDAP_URL: "ldap://172.20.1.69",
        LDAP_BASE_DN: "DC=guadalupana,DC=com,DC=gt",
        LDAP_SERVICE_USER: "pgssantisteban@guadalupana.com.gt",
        LDAP_SERVICE_PASS: "octubre.2024",
        SQL_SERVER: "172.20.1.74",
        PORTSQL: "5533",
        SQL_USER: "Leads",
        SQL_PASSWORD: "T3chn0l0gy",
        SQL_DB: "WSGP",
      },
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "500M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "./logs/error.log",
      out_file: "./logs/out.log",
      merge_logs: true,
    },
  ],
};
